name: sta302-daily-project
channels:
  - conda-forge
dependencies:
  - r-base=4.4.3
  - r-jsonlite=2.0.0
  - r-knitr=1.52
  - r-rmarkdown=2.32
  - pandoc=3.11
  - python=3.12
  - reportlab=4.4
  - pillow=12.0
  - poppler
